@hostname =  http://localhost:9000/teachers

GET {{hostname}}

###

GET {{hostname}}/60e8567e1062be6dd4a2619e

###

POST {{hostname}}/register
Content-Type: application/json

{   
    "personalDetails": {"name": "tom", "DOB": "1989-10-03"},
    "courseDetails" : {"courses":["JS", "Node"]},
    "loginDetails":{
        "username" :"gaurav",
        "password" : "12345678"
    }

}

###

POST {{hostname}}/login/60e8567e1062be6dd4a2619e
Content-Type: application/json


{   
    "username" :"cat",
    "password" : "12345678"
}

###

PUT {{hostname}}/update/60e85eaad7631e710bd6719f
Content-Type: application/json

{   
    "name": "gaurav",
    "username":"gdk",
    "password" : "12345678",
    "courseDetails" : {"courses":["JS", "Node"]}
}

###

DELETE {{hostname}}/delete/60e85eaad7631e710bd6719f

###

GET {{hostname}}